### ISSUE TITLE
Can I try Lens online?

### ISSUE THREAD

**Issue by bitcoinmeetups** [RTradeLtd/Lens#28]
Hi,

Can I try using the Lens search engine online somewhere?

BM

**Comment by bobheadxi** [comment]
Try https://temporal.cloud/lens!

**Comment by postables** [comment]
@bitcoinmeetups Hey there! If you're interested in exploring the dataset currently available via the link that bobheadxi pointed out, you can download it [here](https://gateway.temporal.cloud/ipfs/QmZqSYDQrtWg4LHnqT6DPqa1XUr7u4oeaGcyaTiGHJY3SR). I'll close this issue, feel free to comment and re-open if you feel like your question wasn't properly answered. Additionally I'll update the website link of this repository so other people who may have the same question can get an easy answer :D
